In [19]:
import numpy as np

# Функции специфического вывода данных для LaTeX'a
def print_kekw_matrix(A):
    for i in range(4):
            row = ''
            for j in range(4):
                kek = A[i][j]
                row += str(kek).rstrip('0').rstrip('.') + ' & '
            row = row[:-2]
            row += '\\\\'
            print(row)

def print_matrix(matrix):
    if len(matrix.shape) == 2:
        for i in range(matrix.shape[0]):
            row = ''
            for j in range(matrix.shape[1]):
                kek = matrix[i][j]
                if kek > 0:
                    row += str(round(kek, 5)).rstrip('0').rstrip('.') + ' & '
                else:
                    row += str(round(kek, 4)).rstrip('0').rstrip('.') + ' & '
            row = row[:-2]
            row += '\\\\'
            print(row)
    elif len(matrix.shape) == 1:
        row = ''
        for i in range(matrix.shape[0]):
            kek = matrix[i]
            if kek > 0:
                row += str(round(kek, 5)).rstrip('0').rstrip('.') + ' \\\\ '
            else:
                row += str(round(kek, 4)).rstrip('0').rstrip('.') + ' \\\\ '
        print(row)

# Инициализация данных:
n = 53
beta = 1 - 0.1 * (50 - n)

# Матрица А:
A = np.array([[10 * beta, 1, 2, 3],
              [1, 10 * beta, -3, -2],
              [2, -3, 10 * beta, -1],
              [3, -2, -1, 10 * beta]])
A_copy = A.copy()

print(A)

def get_max_elem(matr):
    D = np.diag(np.diag(matr))
    LU = np.absolute(matr - D)
    amax = np.argmax(LU)
    return amax // LU.shape[1], amax % LU.shape[0]

i = 1

Q_array = []

# Процесс преобразования:
while True:

    max_elem = get_max_elem(A)
    if abs(A[max_elem]) < 0.01:
        break
    if i > 30:
      print("Too many iterations!")
      break
    print(f'\n------------ Iteration {i} ------------')
    print(f'Max element: {max_elem[0] + 1}, {max_elem[1] + 1} = {A[max_elem]}')
    if A[max_elem[0]][max_elem[0]] == A[max_elem[1]][max_elem[1]]:
        print(f'fi = pi/4')
        fi = np.pi / 4
    else:
        fi = (1/2) * np.arctan(2 * A[max_elem[1]][max_elem[0]] / (A[max_elem[0]][max_elem[0]] - A[max_elem[1]][max_elem[1]]))
        print(f'fi = {round(fi, 5)}')



    # Потоковый вывод данных:
    Q = np.eye(A.shape[0])
    Q[max_elem[0]][max_elem[0]] = np.cos(fi)
    Q[max_elem[0]][max_elem[1]] = -np.sin(fi)
    Q[max_elem[1]][max_elem[0]] = np.sin(fi)
    Q[max_elem[1]][max_elem[1]] = np.cos(fi)
    Q_array.append(Q)
    Q_print = np.eye(A.shape[0]).tolist()

    Q_print[max_elem[0]][max_elem[0]] = "cos \\varphi"
    Q_print[max_elem[0]][max_elem[1]] = "-sin \\varphi"
    Q_print[max_elem[1]][max_elem[0]] = "sin \\varphi"
    Q_print[max_elem[1]][max_elem[1]] = "cos \\varphi"
    print('Q:')
    print_kekw_matrix(Q_print)
    print()
    print_matrix(Q)
    print('Q_t')
    print_matrix(Q.T)
    A = Q.T @ A @ Q
    print('A:')
    print_matrix(A)
    i += 1

[[13.  1.  2.  3.]
 [ 1. 13. -3. -2.]
 [ 2. -3. 13. -1.]
 [ 3. -2. -1. 13.]]

------------ Iteration 1 ------------
Max element: 1, 4 = 3.0
fi = pi/4
Q:
cos \varphi & 0 & 0 & -sin \varphi \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
sin \varphi & 0 & 0 & cos \varphi \\

0.70711 & 0 & 0 & -0.7071 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0.70711 & 0 & 0 & 0.70711 \\
Q_t
0.70711 & 0 & 0 & 0.70711 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
-0.7071 & 0 & 0 & 0.70711 \\
A:
16 & -0.7071 & 0.70711 & 0 \\
-0.7071 & 13 & -3 & -2.1213 \\
0.70711 & -3 & 13 & -2.1213 \\
0 & -2.1213 & -2.1213 & 10 \\

------------ Iteration 2 ------------
Max element: 2, 3 = -3.0
fi = pi/4
Q:
1 & 0 & 0 & 0 \\
0 & cos \varphi & -sin \varphi & 0 \\
0 & sin \varphi & cos \varphi & 0 \\
0 & 0 & 0 & 1 \\

1 & 0 & 0 & 0 \\
0 & 0.70711 & -0.7071 & 0 \\
0 & 0.70711 & 0.70711 & 0 \\
0 & 0 & 0 & 1 \\
Q_t
1 & 0 & 0 & 0 \\
0 & 0.70711 & 0.70711 & 0 \\
0 & -0.7071 & 0.70711 & 0 \\
0 & 0 & 0 & 1 \\
A:
16 & 0 & 1 & 0 \\
0 & 10 & 0 & -3 \\
1 & 0 & 1

In [17]:
import functools
print(f'Q[{i-2}]\n')
Q = functools.reduce(lambda a, b : a @ b, Q_array)
print_matrix(Q)

Q[14]

0.01105 & -0.5 & -0.5 & -0.5 \\
-0.011 & 0.5 & -0.5 & -0.5 \\
0.01105 & 0.5 & 0.5 & -0.5 \\
0.01105 & 0.5 & -0.5 & 0.5 \\


In [18]:
A = A_copy
print('Aq1 = ', end='')
print_matrix(A@(Q[:, 0]))
print('Aq2 = ', end='')
print_matrix(A@(Q[:, 1]))
print('Aq3 = ', end='')
print_matrix(A@(Q[:, 2]))
print('Aq4 = ', end='')
print_matrix(A@(Q[:, 3]))

Aq1 = 0.18783 \\ -0.1878 \\ 0.18783 \\ 0.18783 \\ 
Aq2 = -3.5 \\ 3.5 \\ 3.5 \\ 3.5 \\ 
Aq3 = -7.5 \\ -7.5 \\ 7.5 \\ -7.5 \\ 
Aq4 = -6.5 \\ -6.5 \\ -6.5 \\ 6.5 \\ 
