In [ ]:
# Задание 1.1

In [1]:
import numpy as np
from numpy import linalg as lg
import math

# Задание 1.1
N = float(input("Номер студента в группе: "))
alpha = (53-50)/(100)

def norm_A1(matrix: np.ndarray) -> int:
    return max(np.sum(np.absolute(matrix), axis=1))

#def vec_norm(vector: np.ndarray) -> int:
#    return sum(np.absolute(vector))

# Дана СЛАУ: 
A = np.array([[150*(1 + 1/2 * N + alpha), 150*(1 + 1/2 * N), 150*(1 + 1/2 * N)],
                 [150.1*(1 + 1/2 * N), 149.9*(1 + 1/2 * N + alpha), 150*(1 + 1/2 * N)],
                 [149.9*(1 + 1/2 * N), 150*(1 + 1/2 * N), 150.1*(1 + 1/2 * N + alpha)]])

vector_b = np.array([150*(3 + 3/2 * N + alpha), 150*(3 + 3/2 * N + alpha), 150*(3 + 3/2*N + alpha)])

approximate_vector_b = (np.array([150*(3 + 3/2 * N + alpha)*(1 + 0.01), 150*(3 + 3/2 * N + alpha)*(1 - 0.01), 
                                         150*(3 + 3/2*N + alpha)*(1 + 0.01)]))

print("\nЗадание 1.1:\n")
print("Матрица А:\n", A)
print("\nВектор b:", vector_b)
print("\nВектор b приближённой матрицы:", approximate_vector_b)
print("\nОбратная матрца A:\n", lg.inv(A))

# Приближённая СЛАУ имеет вид:

"""approximate_A = np.array([[100*(1 + 1/2 * N), 100(1 + 1/2 * N), 100(1 + 1/2 * N)],
                 [100.1*(1 + 1/2 * N), 99.9(1 + 1/2 * N), 100(1 + 1/2 * N)],
                 [99.9*(1 + 1/2 * N), 100(1 + 1/2 * N), 100.1(1 + 1/2 * N)]])"""

# Найдём число обусловленности матрицы:
print(f"\nНорма матрицы А: {lg.norm(A)}")
print(f"Норма обратной матрицы А: {lg.norm(lg.inv(A))}")
cond_A = norm_A1(A) * norm_A1(lg.inv(A))
print(f"1. Число обусловленности матрицы: {cond_A:.3f} (Использована стандратная норма из задания)")
print(f"2. Число обусловленности полученное функцией cond библиотеки numpy: {lg.cond(A, np.inf):.3f}")
print("3. Таким образом исходная матрицы обусловлена плохо (т.к. cond(A) > 10^(2))\n")

#Найдём относительную погрешность в решении приближенной СЛАУ

delta_b = np.subtract(approximate_vector_b, vector_b)
vector_x = lg.inv(A) @ vector_b
delta_x = lg.inv(A) @ delta_b
relative_error = lg.norm(vector_x, np.inf) / lg.norm(delta_x, np.inf)

print("Вектор b", vector_b)
print("Приближённый вектор b", approximate_vector_b)
print("Вектор погрешностей delta_b:", delta_b)
print("Вектор ответов x:", vector_x)
print("Вектор ошибок delta_x:", delta_x)
print("Норма вектора x:", lg.norm(vector_x, np.inf))
print("Норма вектора delta_x:", lg.norm(delta_x, np.inf))
print("Относительная погрешность: ", relative_error)
print()
print("Норма вектора delta_b:", lg.norm(delta_b, np.inf))
print("Норма вектора b:", lg.norm(vector_b, np.inf))
print("cond(A) * norm(delta_b)/norm(b):", cond_A * lg.norm(delta_b, np.inf) / lg.norm(vector_b, np.inf))

Номер студента в группе: 9

Задание 1.1:

Матрица А:
 [[829.5   825.    825.   ]
 [825.55  828.947 825.   ]
 [824.45  825.    830.053]]

Вектор b: [2479.5 2479.5 2479.5]

Вектор b приближённой матрицы: [2504.295 2454.705 2504.295]

Обратная матрца A:
 [[ 0.15054172 -0.08429439 -0.06584404]
 [-0.10270084  0.16899852 -0.06589409]
 [-0.0474499  -0.08424434  0.13209728]]

Норма матрицы А: 2479.5084122902263
Норма обратной матрицы А: 0.3230357243783606
1. Число обусловленности матрицы: 837.064 (Использована стандратная норма из задания)
2. Число обусловленности полученное функцией cond библиотеки numpy: 837.064
3. Таким образом исходная матрицы обусловлена плохо (т.к. cond(A) > 10^(2))

Вектор b [2479.5 2479.5 2479.5]
Приближённый вектор b [2504.295 2454.705 2504.295]
Вектор погрешностей delta_b: [ 24.795 -24.795  24.795]
Вектор ответов x: [0.99994465 1.00070468 0.99935098]
Вектор ошибок delta_x: [ 4.19015823 -8.37062959  4.1876705 ]
Норма вектора x: 1.0007046778332551
Норма вектора delta_x

In [ ]:
# Задание 1.2
# lambda + alpha = 0.6; F = arctg(x); a = 0; b = 1; alpha = (55-53)/100
# h = (b - a) / (10);

In [1]:
import numpy as np
from numpy import linalg as lg
import math
alpha, a, b = (55 - 53) / 100, 0, 1
h = (b - a) / (10)
lbd = 0.6 - alpha
data = [a + h/2]

# Процедура вывода НЕ numpy матрицы
def print_matrix(matrix: list):
    for i in range(len(matrix)):
        print(matrix[i])
       

# Функция перезаписи матрицы в десятичном виде с точностью до 6 знака после запятой
def remake_matrix(data: list) -> list:
    matrix = []
    for i in range(len(data)):
        array = []
        for j in range(len(data[i])):
            array.append(float("%.6f" %data[i][j]))
        matrix.append(array)
    return matrix

# Создание пустой матрицы 10 на 10:
matrix_A = np.zeros((10, 10))

# Заполнение сетки по условию задачи:
for i in range(1, 10):
    data.append(data[i - 1] + h)
for i in range(len(matrix_A)):
    for j in range(len(matrix_A[i])):
        matrix_A[i][j] = math.atan(data[i] * data[j]) * h
        
# Создание единичной матрицы 10 на 10        
E_matrix = np.identity(10)

# Создание матрицы по заданию
E_lbdA = E_matrix + (lbd * matrix_A)

# Вектор единичек размерностью 10
vector_ones = np.ones(10, dtype="float")

# Создание векторов b и delta_b соотвественно
vector_b = E_lbdA @ vector_ones
vector_delta_b = []
for i in range(10):
    vector_delta_b.append(0.01 * vector_b[i] * (-1)**(i))
    
# Вывод основных данных по матрицам:
print("Матрица А:")
print_matrix(remake_matrix(matrix_A))
print("\nЕдиничная матрица E (10 X 10):")
print_matrix(remake_matrix(E_matrix))
print("\nМатрица lbd * A:")
print_matrix(remake_matrix(lbd * matrix_A))
print("\nМатрица (E + lbd*A):")
print_matrix(remake_matrix(E_lbdA))
print("\nМатрица (E + lbd*A)-1:")
print_matrix(remake_matrix(lg.inv(E_lbdA)))

# Вывод норм и процесс решения СЛАУ
print("\nНорма матрицы (E + lbd*A):", lg.norm(E_lbdA, np.inf))
print("\nНорма матрицы (E + lbd*A)-1:", lg.norm(lg.inv(E_lbdA), np.inf))
print("\nЧисло обусловленности матрицы А:", lg.cond(E_lbdA, np.inf))
print("\nВектор b\n", vector_b)
print("\nНорма вектора b:", lg.norm(vector_b, np.inf))
print("\nВектор delta_b:", np.array(vector_delta_b))
print("\nНорма вектора delta_b\n:", lg.norm(vector_delta_b, np.inf))
b = vector_b + vector_delta_b
relative_error = lg.inv(E_lbdA) @ vector_delta_b
print("\nВектор b + вектор delta_b\n", b)

# Найдём решение x = (E + lbd*A)-1 * b
print("\nРешение приближённой СЛАУ\n", lg.solve(E_lbdA, b))

# Найдём относительную погрешность решения приближённой СЛАУ
print("\nВектор относительных погрешностей:\n", relative_error)
print("\nАбсолютная ошибка вычисления:", lg.norm(relative_error, np.inf))
print()

# Найдём решение СЛАУ, которая получается из СЛАУ (3) делением каждого i-го уравнения на число bi+delta_bi
work_B = []
for i in range(len(E_lbdA)):
    data = []
    for j in range(len(E_lbdA[i])):
        data.append(E_lbdA[i][j] / b[i])
    work_B.append(data)
matrix_B = np.array(work_B)
x_solve = lg.inv(matrix_B) @ vector_ones
relative_error = x_solve - vector_ones
print("\nМатрица B:")
print_matrix(remake_matrix(matrix_B))
print("\nМатрица B-1:")
print_matrix(remake_matrix(lg.inv(matrix_B)))
print("\nВектор решений изменённой СЛАУ:\n", x_solve)
print("\nВектор относительных погрешностей:\n", relative_error)
print("\nАбсолютная погрешность:\n", lg.norm(relative_error, np.inf))

Матрица А:
[0.00025, 0.00075, 0.00125, 0.00175, 0.00225, 0.002749, 0.003249, 0.003748, 0.004247, 0.004746]
[0.00075, 0.00225, 0.003748, 0.005245, 0.00674, 0.008231, 0.009719, 0.011203, 0.012682, 0.014155]
[0.00125, 0.003748, 0.006242, 0.008728, 0.011203, 0.013664, 0.016109, 0.018535, 0.020939, 0.023318]
[0.00175, 0.005245, 0.008728, 0.012189, 0.015622, 0.019017, 0.022369, 0.025671, 0.028916, 0.0321]
[0.00225, 0.00674, 0.011203, 0.015622, 0.01998, 0.024262, 0.028456, 0.03255, 0.036533, 0.040399]
[0.002749, 0.008231, 0.013664, 0.019017, 0.024262, 0.029375, 0.034334, 0.039124, 0.043731, 0.048149]
[0.003249, 0.009719, 0.016109, 0.022369, 0.028456, 0.034334, 0.039975, 0.04536, 0.050476, 0.055319]
[0.003748, 0.011203, 0.018535, 0.025671, 0.03255, 0.039124, 0.04536, 0.051239, 0.056754, 0.061907]
[0.004247, 0.012682, 0.020939, 0.028916, 0.036533, 0.043731, 0.050476, 0.056754, 0.062567, 0.06793]
[0.004746, 0.014155, 0.023318, 0.0321, 0.040399, 0.048149, 0.055319, 0.061907, 0.06793, 0.073419]

Е